baseURL = "https://diylove.github.io/"
title = "DIY💔"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "待填0"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "待填1" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "待填2"

    # The name to display in the copyright section in the footer
    copyrightname = ""

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    # github = "https://github.com/diylove/wiki"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = ""

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = "MADE WITH 💔 BY CONTRIBUTORS | CC BY-SA 4.0"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "GITHUB.COM/DIYLOVE"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "ABOUT"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "GUDIES"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true